services:
  - type: web
    name: leaddesk-mini-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_SEED_PASSWORD
        sync: false
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        sync: false
